type Post{
    "Unique primary key."
    id: ID!

    "Non-unique post name."
    name: String!

    "User ID."
    user_id: String!

    "When the account was created."
    created_at: DateTime!

    "When the account was last updated."
    updated_at: DateTime!
}